import pyautogui

pyautogui.press('win')
pyautogui.sleep(1)
pyautogui.write('google chrome', interval=0.2)
pyautogui.press('enter')
pyautogui.sleep(2)
pyautogui.hotkey('alt', 'd')
pyautogui.press('enter')
pyautogui.write('instagram.com')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(0.5)
pyautogui.write('@gustavo_.xw')
pyautogui.sleep(0.5)
pyautogui.press('tab')
pyautogui.write('112787072-5')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.click()
pyautogui.sleep(30)
pyautogui.hotkey('alt', 'f4')  
